public class LobbyInfo
{
    public List<int> lobbyVRSearchList = new List<int>();
    public LobbyReddotInfo lobbyReddotInfo = new LobbyReddotInfo();
    public List<UserNpc> userNpcInfoList = new List<UserNpc>();
    public List<int> guestNPCList = new List<int>();
    public int currentVisitGuestID;
    public int currentVisitGuestIndex;
    public bool newHeroVisit;
    public int remainHeroVisitTimeSec;
    public bool hawkCollectAble;
    public EventPacketInfo eventPacketInfo = new EventPacketInfo();
    public List<NoticeInfo> noticeList = new List<NoticeInfo>();
    public List<PackageBannerInfo> packageBannerInfoList = new List<PackageBannerInfo>();
    public List<int> disableDropInteractiveList = new List<int>();
    public bool isGuildKickOut;
    public GuildMemberInfo guildMemberInfo = new GuildMemberInfo();
    public int remainDailyResetTimeSEC;
    public List<QuestProgressInfo> questProgressInfoList = new List<QuestProgressInfo>();
    public bool didDailyResetToday;
    public LobbyRandomShopInfo randomShopInfo = new LobbyRandomShopInfo();
    public ClientSendFinalBossSeasonInfo clientSendFinalBossSeasonInfo = new ClientSendFinalBossSeasonInfo();
    public ClientSendFinalBossSeasonShopInfo clientSendFinalBossSeasonShopInfo = new ClientSendFinalBossSeasonShopInfo();
    public List<UserHeroGachaGaugeInfo> userHeroGachaGaugeInfoList = new List<UserHeroGachaGaugeInfo>();
    public byte userAgeLevel;
    public UserMonthlyStageInfo monthlyInfo = new UserMonthlyStageInfo();
    public bool gaugeEventFreeChargeAble;
    public byte currentSeasonGroup;
    public List<TournamentDisplayInfo> tournamentDiplayInfoList = new List<TournamentDisplayInfo>();
    public List<UserADViewInfo> userAdViewInfoList = new List<UserADViewInfo>();
    public ClientSendBossWarInfo clientSendBossWarInfo = new ClientSendBossWarInfo();
    public ArenaLeagueGrade arenaRealTimePvpLowGrade;
    public byte arenaRealTimePvpLowGradeNumber;
    public List<UserFurniture> updateUserFurnitureList = new List<UserFurniture>();
    public bool firstDiaBuy;
    public bool isGuildWarRejoinInfoExists;
    public GuildWarScheduleInfo currentGuildWarScheduleInfo = new GuildWarScheduleInfo();
    public bool isGuildWarSelected;
    public int guildWarRejoinInfoReaminTTLSec;
    public List<GuildWarSelectionInfo> guildWarSelectionInfoList = new List<GuildWarSelectionInfo>();
    public bool isGuildWarRankRewardable;
    public bool activeSpecialGuestBuff;
    public bool popupSpecialGuestBuff;
    public bool popupPatrolMissionOpen;
    public TowerStageInfo towerStageInfo = new TowerStageInfo();
    public TowerStageHeroInfo towerStageHeroInfo = new TowerStageHeroInfo();
    public TowerStageInfo disasterTowerStageInfo = new TowerStageInfo();
    public TowerStageHeroInfo disasterTowerStageHeroInfo = new TowerStageHeroInfo();
    public int lowerLeagueTableID;
    public int guildBossSeasonID;
    public int guildBossGroupID;
    public GuildWarLowScheduleInfo currentGuildWarLowScheduleInfo = new GuildWarLowScheduleInfo();
    public bool isGuildWarLowRejoinInfoExists;
    public int guildWarLowRejoinInfoReaminTTLSec;
    public bool isGuildWarLowPointRewardable;
    public int guildWarLowLastSeason;
    public int guildWarLowOpponentGuildSN;
    public bool isGuildWarPrevSeasonSelected;
    public GuildAttendanceStatus guildAttendanceStatus = new GuildAttendanceStatus();
    public GuildNoticeInfo guildNoticeInfo = new GuildNoticeInfo();
    public List<int> guildMarkList = new List<int>();
    public GambleTimeSwitchLobbyInfo gambleTimeSwitchLobbyInfo = new GambleTimeSwitchLobbyInfo();
    public int growthPoint;
    public List<ConstellationStoneInfo> stackConstellationStoneInfoList = new List<ConstellationStoneInfo>();
    public bool isCreatureNestChallengeRewardable;
    public bool isCreatureNestBlueDotOn;
    public LimitedCostumeInfo removeLimitedCostumeInfo = new LimitedCostumeInfo();
    public int remainConstellationChaosChargeSec;
    public ArenaRealTimePvp_LoginInfo arenaRealTimePvpSimpleInfo = new ArenaRealTimePvp_LoginInfo();
    public ClientSendEventMazeSeasonShopInfo clientSendEventMazeSeasonShopInfo = new ClientSendEventMazeSeasonShopInfo();
    public ClientSendHeroLeagueInfo clientSendHeroLeagueInfo = new ClientSendHeroLeagueInfo();
    public ClientSendHeroLeagueSeasonShopInfo clientSendHeroLeagueSeasonShopInfo = new ClientSendHeroLeagueSeasonShopInfo();
    public GuildOrderMissionInfoClientSend guildOrderMissionInfoClientSend = new GuildOrderMissionInfoClientSend();
    public List<UserGuildOrderMissionInfo> userGuildOrderMissionInfoClientSend = new List<UserGuildOrderMissionInfo>();
    public CreatureNestColosseumSeasonInfo creatureColosseumSeasonInfo = new CreatureNestColosseumSeasonInfo();
    public UserDemonLordInfoToClientSend demonLordInfo = new UserDemonLordInfoToClientSend();
    public int diaShopBuyRemainTimeSec;
}