public class LoginUserResultInfo
{
    public long usn;
    public int sessionKey;
    public string name = string.Empty;
    public int nicknameChangeCount;
    public int exp;
    public int vipExp;
    public List<NoticeInfo> noticeList = new List<NoticeInfo>();
    public List<UserHero> userHeroList = new List<UserHero>();
    public List<UserSkin> userSkinList = new List<UserSkin>();
    public List<UserWeapon> userWeaponList = new List<UserWeapon>();
    public List<UserCommonItem> userCommonItemList = new List<UserCommonItem>();
    public UserExtensionData extensionData = new UserExtensionData();
    public List<UserTeam> userTeamList = new List<UserTeam>();
    public OtherPlayerTeamInfo arenaRankingDefenceTeamInfo = new OtherPlayerTeamInfo();
    public List<OtherPlayerTeamInfo> arenaSmashDefenceTeamInfoList = new List<OtherPlayerTeamInfo>();
    public List<OtherPlayerTeamInfo> tournamentTeamInfoList = new List<OtherPlayerTeamInfo>();
    public List<APInfo> userAPInfoList = new List<APInfo>();
    public StageInfo userStageInfo = new StageInfo();
    public string userWantToSay = string.Empty;
    public int userMaxFriendCount;
    public UserDailyReset userDailyReset = new UserDailyReset();
    public List<UserRecipeInfo> userRecipeInfoList = new List<UserRecipeInfo>();
    public UserBasePointContentsInfo userBasePointContentsInfo = new UserBasePointContentsInfo();
    public List<int> autoStartQuestIDList = new List<int>();
    public List<QuestProgressInfo> userQuestProgressInfoList = new List<QuestProgressInfo>();
    public int missionAchieveRewardIndex;
    public GuildMemberInfo userGuildMemberInfo = new GuildMemberInfo();
    public string userGuildName = string.Empty;
    public int frinedCode;
    public int playingDestroyRoomSN;
    public List<DestroyDiscoverInfo> userDestroyDiscoverInfoList = new List<DestroyDiscoverInfo>();
    public byte userAgeLevel;
    public List<UserTutorialInfo> userTutorialInfoList = new List<UserTutorialInfo>();
    public List<ChatQuickMessageInfo> userQuickMessageInfoList = new List<ChatQuickMessageInfo>();
    public List<ChatStampBookmarkInfo> userStampBookmarkInfoList = new List<ChatStampBookmarkInfo>();
    public bool rePayFlag;
    public List<UserNpc> userNpcList = new List<UserNpc>();
    public List<MarketMissionInfo> platformMissionInfoList = new List<MarketMissionInfo>();
    public FoodBuffInfo foodBuffInfo = new FoodBuffInfo();
    public DestroyInviteOption destroyInviteOption;
    public bool isGuildInvitationOn;
    public int userNicknameChangeAvailableRemainSec;
    public List<UserCostumeSkin> userCostumeSkin = new List<UserCostumeSkin>();
    public List<UserCostumeWeapon> userCostumeWeapon = new List<UserCostumeWeapon>();
    public List<UserCostumeHead> userCostumeHead = new List<UserCostumeHead>();
    public List<UserCostumeCraftUpgradeInfo> userCostumeCraftUpgradeInfoList = new List<UserCostumeCraftUpgradeInfo>();
    public List<UserPackageInfo> userPackageInfoList = new List<UserPackageInfo>();
    public List<UserPackageInfo> userDiaShopPackageInfoList = new List<UserPackageInfo>();
    public int mainSkinID;
    public int lobbyUniqueInteractiveFlag;
    public QuestChapterClearInfo questChapterClearInfo = new QuestChapterClearInfo();
    public byte loveRewardSeq;
    public GuildInfo userGuildInfo = new GuildInfo();
    public List<GuildMemberInfo> guildMemberInfoList = new List<GuildMemberInfo>();
    public bool isCheatEnable;
    public bool realTimePvpRewardAble;
    public List<UserBuffInfo> userBuffInfoList = new List<UserBuffInfo>();
    public List<UserHeroGachaGaugeInfo> userHeroGachaGaugeInfoList = new List<UserHeroGachaGaugeInfo>();
    public int eventMissionAchieveRewardIndex;
    public byte restDayCount;
    public bool isPvpLowerClear;
    public DateTime accountCreateTime;
    public List<UserFurniture> userFurnitureList = new List<UserFurniture>();
    public List<FriendInfo> friendInfoList = new List<FriendInfo>();
    public List<UserFrozenAsset> userFrozenAssetList = new List<UserFrozenAsset>();
    public ArenaLeagueGrade arenaRealTimePvpGrade;
    public List<WeaponUpgradeFailGaugeInfo> userWeaponUpgradeFailGaugeList = new List<WeaponUpgradeFailGaugeInfo>();
    public UserMonthlyStageInfo monthlyInfo = new UserMonthlyStageInfo();
    public List<int> eventMissionCompleteRewardInfoList = new List<int>();
    public List<GuildBossRankPoint> guildBossRankPointList = new List<GuildBossRankPoint>();
    public GuildBossRankPointReward guildBossRankPointReward = new GuildBossRankPointReward();
    public bool isDecisionPlayAble;
    public List<UserMusic> userMusicList = new List<UserMusic>();
    public bool isGuideListRewarded;
    public byte guideListStep;
    public int playTitleID;
    public int playMusicID;
    public byte musicInstrumentID;
    public long freePackageReward;
    public byte seasonPassAccumulationCount;
    public List<UserPackageMissionInfo> userPackageMissionInfoList = new List<UserPackageMissionInfo>();
    public List<UserFinalBossRankPoint> userFinalBossRankPointList = new List<UserFinalBossRankPoint>();
    public List<int> getPlayTitleList = new List<int>();
    public List<ReverseSeasonInfo> reverseSeasonInfoList = new List<ReverseSeasonInfo>();
    public GuildWarUserSquadInfo guildWarUserSquadInfo = new GuildWarUserSquadInfo();
    public DestroyDisasterDicoverInfo destroyDisasterInfo = new DestroyDisasterDicoverInfo();
    public UserEventBingoInfo userEventBingoInfo = new UserEventBingoInfo();
    public List<StageTicketClearInfo> userStageTicketClearInfoList = new List<StageTicketClearInfo>();
    public ArenaSmashLobbyInfo arenaSmashLobbyInfo = new ArenaSmashLobbyInfo();
    public List<UserHeroPassiveGroupInfo> heroPassiveGroupInfoList = new List<UserHeroPassiveGroupInfo>();
    public List<GuildWarDefenceTeamInfo> guildWarDefenceTeamInfoList = new List<GuildWarDefenceTeamInfo>();
    public List<GuildWarLowDefenceTeamInfo> guildWarLowDefenceTeamInfoList = new List<GuildWarLowDefenceTeamInfo>();
    public List<int> artifactCardIdList = new List<int>();
    public List<UserArtifactTeamInfo> artifactTeamInfoList = new List<UserArtifactTeamInfo>();
    public List<UserArtifactUnionInfo> artifactUnionInfoList = new List<UserArtifactUnionInfo>();
    public List<NorthGrimBookCategoryInfo> northGrimBookCategoryInfoList = new List<NorthGrimBookCategoryInfo>();
    public ConstellationSystemInfo constellationInfo = new ConstellationSystemInfo();
    public LobbyVisualType lobbyVisualType;
    public int materialFusionPoint;
    public int battleEncounter;
    public int attendanceHeroID;
    public int activeAttendanceHeroID;
    public List<DailyFreeGambleInfoClientSend> dailyFreeGambleInfoClientSend = new List<DailyFreeGambleInfoClientSend>();
    public GuildOrderMissionInfoClientSend guildOrderMissionInfoClientSend = new GuildOrderMissionInfoClientSend();
    public List<UserGuildOrderMissionInfo> userGuildOrderMissionInfoClientSend = new List<UserGuildOrderMissionInfo>();
}