public class UserDailyReset
{
    public byte barrelCount;
    public byte friendDeleteCount;
    public byte floorSearchValue1;
    public byte floorSearchValue2;
    public byte floorSearchValue3;
    public byte floorSearchValue4;
    public List<QuestProgressInfo> lobbyQuestProgressInfoList = new List<QuestProgressInfo>();
    public ClientSendUserAttendanceInfo attendanceInfo = new ClientSendUserAttendanceInfo();
    public List<int> birthdayGuestIDList = new List<int>();
    public int basepointDailyReward;
    public byte cleanTableCount;
    public byte serveBeerCount;
    public byte playJukeboxCount;
    public byte elizabethTouchCount;
    public byte hawkAngerCount;
    public byte meliodasCookingCount;
    public byte barrelFellowCount;
    public int friendPointGainCount;
    public byte heroGachaOneDiaCount;
    public byte helbramCount;
    public byte friendCookingEatCount;
    public byte guildDonationCount1;
    public byte guildDonationCount2;
    public byte guildShopResetCount;
    public byte eventExchangeBoxGachaResetCount;
    public byte eventGagueChargeFreeCount;
    public byte eventGagueChargetPoint;
    public byte guildDonationContribution;
    public StageInfo stageInfo = new StageInfo();
    public List<UserPackageInfo> userPackageInfoList = new List<UserPackageInfo>();
    public List<UserPackageInfo> userDiaShopPackageInfoList = new List<UserPackageInfo>();
    public List<GuildMissionInfo> guildMissionInfoList = new List<GuildMissionInfo>();
    public EventPacketInfo eventPacketInfo = new EventPacketInfo();
    public byte inviteSpecialGuestCount;
    public byte trainingStageRefreshCount;
    public LobbyGuestInfo lobbyGuestInfo = new LobbyGuestInfo();
    public List<UserADViewInfo> userAdViewInfoList = new List<UserADViewInfo>();
    public List<SubdueBossPlayInfo> subdueBossPlayInfoList = new List<SubdueBossPlayInfo>();
    public PatrolInfo patrolInfo = new PatrolInfo();
    public byte eventLadderPlayCount;
    public byte arenaSmashTeamUpdateCount;
    public byte arenaSmashWinRewardedCount;
    public byte eventTreasureHuntDiceCount;
    public byte guildExpBoostStack;
    public byte destroyLiveJoinCount;
    public byte lobbyCollectPassiveUseCount;
    public byte freeClearTicketUseCount;
    public byte gambleFreeCount;
    public List<DailyFreeGambleInfoClientSend> dailyFreeGambleInfoClientSend = new List<DailyFreeGambleInfoClientSend>();
    public List<ItemResultInfo> itemResultInfoList = new List<ItemResultInfo>();
    public ConstellationChaosInfo constellationChaosInfo = new ConstellationChaosInfo();
    public GuildOrderMissionInfoClientSend guildOrderMissionInfoClientSend = new GuildOrderMissionInfoClientSend();
    public List<UserGuildOrderMissionInfo> userGuildOrderMissionInfoClientSend = new List<UserGuildOrderMissionInfo>();
}